name: GMVRgrid
favicon: null
layout_spectrum: 0.5360389507841319
typography_spectrum: 0.5972913254518062
title: GMVRGrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2868674201890826
  lightness: 0.3445104791317135
  saturation: 0.37210408225655556
  rhythmicContrast: 0.07275165244936943
purpose: []
